In [1]:
import pandas as pd
data={'Name': ['A', 'B', 'C', 'D'], 
 'Age': [25, 30, 22, 28], 
 'Salary': [50000, 60000, 45000, 70000]}
df=pd.DataFrame(data)

In [2]:
df.iloc[0:2]


Name  Age  Salary
0    A   25   50000
1    B   30   60000

In [3]:
df=pd.read_csv("data.csv")

In [4]:
df.shape

(12, 6)

In [5]:
df.columns

Index(['Actor', 'Film', 'Year', 'Genre', 'BoxOffice(INR Crore)', 'IMDb'], dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Actor                 12 non-null     object 
 1   Film                  12 non-null     object 
 2   Year                  12 non-null     int64  
 3   Genre                 12 non-null     object 
 4   BoxOffice(INR Crore)  12 non-null     int64  
 5   IMDb                  12 non-null     float64
dtypes: float64(1), int64(2), object(3)
memory usage: 708.0+ bytes


In [7]:
df.dtypes

Actor                    object
Film                     object
Year                      int64
Genre                    object
BoxOffice(INR Crore)      int64
IMDb                    float64
dtype: object

In [8]:
import pandas as pd
data={'Name': ['A', 'B', 'C', 'D'], 
 'Age': [25, 30, 22, 28], 
 'Salary': [50000, 60000, 45000, 70000]}
df=pd.DataFrame(data)
df.loc[0:4,["Age"]]

Age
0   25
1   30
2   22
3   28

In [9]:
df['Age']

0    25
1    30
2    22
3    28
Name: Age, dtype: int64

In [10]:
df.query("Salary>50000")

Name  Age  Salary
1    B   30   60000
3    D   28   70000

In [11]:
df['Bonus']=df['Salary']/10

In [12]:
df

Name  Age  Salary   Bonus
0    A   25   50000  5000.0
1    B   30   60000  6000.0
2    C   22   45000  4500.0
3    D   28   70000  7000.0

In [13]:
df.sort_values('Age',ascending=False)

Name  Age  Salary   Bonus
1    B   30   60000  6000.0
3    D   28   70000  7000.0
0    A   25   50000  5000.0
2    C   22   45000  4500.0

In [14]:
df.groupby('Age')['Salary'].mean()

Age
22    45000.0
25    50000.0
28    70000.0
30    60000.0
Name: Salary, dtype: float64

In [15]:
import numpy as np
data = {
    'Name': ['A', 'B', 'C', 'D', 'E'],
    'Age': [25, np.nan, 22, np.nan, 30],
    'Salary': [50000, 60000, np.nan, 70000, 65000]
}
df=pd.DataFrame(data)

In [16]:
df

Name   Age   Salary
0    A  25.0  50000.0
1    B   NaN  60000.0
2    C  22.0      NaN
3    D   NaN  70000.0
4    E  30.0  65000.0

In [17]:
df[df.isnull().any(axis=1)]

Name   Age   Salary
1    B   NaN  60000.0
2    C  22.0      NaN
3    D   NaN  70000.0

In [21]:
df.isnull()

Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True
3  False   True   False
4  False  False   False

In [22]:
df.isnull().sum()

Name      0
Age       2
Salary    1
dtype: int64

In [23]:
df['Age']=df['Age'].fillna(df['Age'].mean())

In [24]:
df

Name        Age   Salary
0    A  25.000000  50000.0
1    B  25.666667  60000.0
2    C  22.000000      NaN
3    D  25.666667  70000.0
4    E  30.000000  65000.0

In [25]:
d1 = {'ID':[1,2,3], 'Name':['A','B','C']}

d2 = {'ID':[1,2,4], 'Marks':[85,90,75]}
df1=pd.DataFrame(d1)
df2=pd.DataFrame(d2)

In [26]:
pd.merge(df1,df2,on='ID')

ID Name  Marks
0   1    A     85
1   2    B     90

In [28]:
data={ 'Name': ['A','B','C','D','E'],
'Age': [25, np.nan, 22, np.nan, 30],
'Salary': [50000, 60000, np.nan, 70000, 65000],
'Department': ['HR','IT','IT','Finance','HR']
}
df=pd.DataFrame(data)


In [29]:
df

Name   Age   Salary Department
0    A  25.0  50000.0         HR
1    B   NaN  60000.0         IT
2    C  22.0      NaN         IT
3    D   NaN  70000.0    Finance
4    E  30.0  65000.0         HR

In [30]:
df[df.isnull().any(axis=1)]

Name   Age   Salary Department
1    B   NaN  60000.0         IT
2    C  22.0      NaN         IT
3    D   NaN  70000.0    Finance

In [32]:
df['Age'].fillna(df['Age'].mean(),inplace=True)
df['Salary'].fillna(df['Salary'].median(),inplace=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_27960\645796033.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)


In [33]:
df

Name        Age   Salary Department
0    A  25.000000  50000.0         HR
1    B  25.666667  60000.0         IT
2    C  22.000000  62500.0         IT
3    D  25.666667  70000.0    Finance
4    E  30.000000  65000.0         HR

In [34]:
df[["Name","Salary"]]

Name   Salary
0    A  50000.0
1    B  60000.0
2    C  62500.0
3    D  70000.0
4    E  65000.0

In [42]:
df.query("Salary>55000 and Department=='IT' ")

Name        Age   Salary Department
1    B  25.666667  60000.0         IT
2    C  22.000000  62500.0         IT

In [44]:
df.groupby("Department")[["Age","Salary"]].mean()

Age   Salary
Department                    
Finance     25.666667  70000.0
HR          27.500000  57500.0
IT          23.833333  61250.0

In [46]:
df.pivot_table(index="Department",values="Salary",aggfunc="mean")

Salary
Department         
Finance     70000.0
HR          57500.0
IT          61250.0

In [48]:
def salary(x):
    if x>65000:
        return "High"
    elif x>=50000 :
        return "Medium"
    else:
        return "Low"
df["Rank"]=df["Salary"].apply(salary)        

In [49]:
df

Name        Age   Salary Department    Rank
0    A  25.000000  50000.0         HR  Medium
1    B  25.666667  60000.0         IT  Medium
2    C  22.000000  62500.0         IT  Medium
3    D  25.666667  70000.0    Finance    High
4    E  30.000000  65000.0         HR  Medium

In [51]:
df['Salary_Level'] = pd.cut(df['Salary'], bins=[0,50000,65000, np.inf], labels=['Low','Medium','High'],right=False)
df

Name        Age   Salary Department    Rank Salary_Level
0    A  25.000000  50000.0         HR  Medium       Medium
1    B  25.666667  60000.0         IT  Medium       Medium
2    C  22.000000  62500.0         IT  Medium       Medium
3    D  25.666667  70000.0    Finance    High         High
4    E  30.000000  65000.0         HR  Medium         High

In [95]:
import pandas as pd
import numpy as np

data = {
    'Name': ['A','B','C','D','E','F'],
    'Age': [25, np.nan, 22, 28, np.nan, 35],
    'Salary': [50000, 60000, np.nan, 70000, 65000, 80000],
    'Department': ['HR','IT','IT','Finance','HR','Finance']
}
df = pd.DataFrame(data)
df

Name   Age   Salary Department
0    A  25.0  50000.0         HR
1    B   NaN  60000.0         IT
2    C  22.0      NaN         IT
3    D  28.0  70000.0    Finance
4    E   NaN  65000.0         HR
5    F  35.0  80000.0    Finance

In [96]:
df[df.isnull().any(axis=1)]

Name   Age   Salary Department
1    B   NaN  60000.0         IT
2    C  22.0      NaN         IT
4    E   NaN  65000.0         HR

In [97]:
df["Age"]=df["Age"].fillna(df['Age'].mean())

In [98]:
df["Salary"]=df["Salary"].fillna(df['Salary'].median())

In [99]:
df

Name   Age   Salary Department
0    A  25.0  50000.0         HR
1    B  27.5  60000.0         IT
2    C  22.0  65000.0         IT
3    D  28.0  70000.0    Finance
4    E  27.5  65000.0         HR
5    F  35.0  80000.0    Finance

In [100]:
df["Salary_level"]=pd.cut(df["Salary"],bins=[0,50000,65000,np.inf],labels=["Low","Medium","High"],right=False)

In [101]:
df

Name   Age   Salary Department Salary_level
0    A  25.0  50000.0         HR       Medium
1    B  27.5  60000.0         IT       Medium
2    C  22.0  65000.0         IT         High
3    D  28.0  70000.0    Finance         High
4    E  27.5  65000.0         HR         High
5    F  35.0  80000.0    Finance         High

In [102]:
df.query("Salary>50000 and Department == 'IT'")

Name   Age   Salary Department Salary_level
1    B  27.5  60000.0         IT       Medium
2    C  22.0  65000.0         IT         High

In [103]:
df.groupby("Department")["Salary"].mean()

Department
Finance    75000.0
HR         57500.0
IT         62500.0
Name: Salary, dtype: float64

In [104]:
df.pivot_table(index="Department",values="Salary",aggfunc="mean")

Salary
Department         
Finance     75000.0
HR          57500.0
IT          62500.0

In [105]:
a=np.array(df["Salary"])

In [106]:
a

array([50000., 60000., 65000., 70000., 65000., 80000.])

In [107]:
b=np.array(df["Age"])

In [108]:
b

array([25. , 27.5, 22. , 28. , 27.5, 35. ])

In [109]:
np.stack((a,b),axis=1)

array([[5.00e+04, 2.50e+01],
       [6.00e+04, 2.75e+01],
       [6.50e+04, 2.20e+01],
       [7.00e+04, 2.80e+01],
       [6.50e+04, 2.75e+01],
       [8.00e+04, 3.50e+01]])

In [110]:
df.loc[df['Salary'] > 75000, 'Salary'] = np.inf


In [111]:
df


Name   Age   Salary Department Salary_level
0    A  25.0  50000.0         HR       Medium
1    B  27.5  60000.0         IT       Medium
2    C  22.0  65000.0         IT         High
3    D  28.0  70000.0    Finance         High
4    E  27.5  65000.0         HR         High
5    F  35.0      inf    Finance         High

In [112]:
salary_array = df['Salary'].to_numpy()
age_array = df['Age'].to_numpy()

stacked = np.stack((salary_array, age_array), axis=1)
stacked

array([[5.00e+04, 2.50e+01],
       [6.00e+04, 2.75e+01],
       [6.50e+04, 2.20e+01],
       [7.00e+04, 2.80e+01],
       [6.50e+04, 2.75e+01],
       [     inf, 3.50e+01]])

In [116]:
df.loc[df["Age"]>25,"Age"]=0

In [117]:
df


Name   Age   Salary Department Salary_level
0    A  25.0  50000.0         HR       Medium
1    B   0.0  60000.0         IT       Medium
2    C  22.0  65000.0         IT         High
3    D   0.0  70000.0    Finance         High
4    E   0.0  65000.0         HR         High
5    F   0.0      inf    Finance         High

In [118]:
import pandas as pd
import numpy as np

employees = pd.DataFrame({
    'EmpID': [101, 102, 103, 104, 105, 106],
    'Name': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Department': ['Sales','IT','Sales','Finance','IT','Finance'],
    'Age': [25, np.nan, 30, 28, np.nan, 40],
    'Salary': [50000, 60000, np.nan, 70000, 65000, 80000]
})
sales = pd.DataFrame({
    'EmpID': [101,101,102,103,104,106,106],
    'Month': ['Jan','Feb','Jan','Jan','Feb','Jan','Feb'],
    'Sales': [20000, 22000, 25000, np.nan, 30000, 27000, 28000]
})
employees["Age"]=employees["Age"].fillna(employees["Age"].median())
employees["Salary"]=employees["Salary"].fillna(employees["Salary"].mean())
sales["Sales"]=sales["Sales"].fillna(0)

In [119]:
employees

EmpID Name Department   Age   Salary
0    101    A      Sales  25.0  50000.0
1    102    B         IT  29.0  60000.0
2    103    C      Sales  30.0  65000.0
3    104    D    Finance  28.0  70000.0
4    105    E         IT  29.0  65000.0
5    106    F    Finance  40.0  80000.0

In [120]:
sales

EmpID Month    Sales
0    101   Jan  20000.0
1    101   Feb  22000.0
2    102   Jan  25000.0
3    103   Jan      0.0
4    104   Feb  30000.0
5    106   Jan  27000.0
6    106   Feb  28000.0

In [126]:
df=pd.merge(employees,sales,on="EmpID")

In [128]:
df.pivot_table(index="Department",columns="Month",values="Salary",aggfunc="sum")

Month            Feb       Jan
Department                    
Finance     150000.0   80000.0
IT               NaN   60000.0
Sales        50000.0  115000.0