In [1]:
import numpy as np
arr = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])


In [2]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [4]:
arr[0][1]
arr[0,1]

np.int64(2)

In [5]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [6]:
arr3D = np.array([
    [[1, 2, 3], 
     [4, 5, 6]],
    
[[7, 8, 9],
 [10, 11, 12]]

])

In [7]:
print(arr3D[:, 0, :])

[[1 2 3]
 [7 8 9]]


In [8]:
arr3D[:, 0, :] = 0

In [9]:
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])

In [10]:
arr3D=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
arr3D.reshape(6,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [12]:
A=arr3D.flatten()

In [13]:
A.reshape((3,3,2))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])