In [22]:
import numpy as np
n=np.random.randint(1,101,(3,3))

In [23]:
n

array([[50, 81, 48],
       [ 7, 59, 38],
       [24, 12, 42]], dtype=int32)

In [4]:
n=np.linspace(0,10,20)

In [5]:
n

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [6]:
n=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
n.reshape((4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [7]:
n=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
n[n%2==0]

array([ 2,  4,  6,  8, 10])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a*b

array([ 4, 10, 18])

In [10]:
n=np.random.randint(1,100,15)

In [14]:
n.mean()


np.float64(42.53333333333333)

In [13]:
n.sum()


np.int64(638)

In [15]:
n.std()

np.float64(26.474809830394545)

In [18]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [25]:
n[ n>50 ] =-1

In [26]:
n

array([[50, -1, 48],
       [ 7, -1, 38],
       [24, 12, 42]], dtype=int32)

In [27]:
n=np.arange(6)

In [28]:
n[::-1]

array([5, 4, 3, 2, 1, 0])